DROP TABLE IF EXISTS `TBL_BATCH_NUM`;  
CREATE TABLE `TBL_BATCH_NUM` (
	`BATCH_DATE` VARCHAR(11) NOT NULL,
	`LAST_DATE` VARCHAR(8) NOT NULL,
	`BATCH_NUM` VARCHAR(4) NOT NULL,
	`CUR_BATCH_NUM` VARCHAR(12) NOT NULL,
	`LST_BATCH_NUM` VARCHAR(12) NOT NULL,
	`NXT_BATCH_NUM` VARCHAR(12) NOT NULL,
	`UPD_TIME` VARCHAR(14) NOT NULL,
	PRIMARY KEY (`UPD_TIME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;