DROP TABLE IF EXISTS `TBL_BATCH_CFG`;  
CREATE TABLE `TBL_BATCH_CFG` (
	`BATCH_NUM` VARCHAR(4) NOT NULL,
	`BATCH_YEAR` VARCHAR(4) NULL DEFAULT NULL,
	`BATCH_MON` VARCHAR(2) NULL DEFAULT NULL,
	`BATCH_DATE` VARCHAR(2) NULL DEFAULT NULL,
	`BATCH_HOUR` VARCHAR(2) NULL DEFAULT NULL,
	`BATCH_MIN` VARCHAR(2) NULL DEFAULT NULL,
	`BATCH_SEC` VARCHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`BATCH_NUM`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
